import type { Bead } from "@/types/molecule";
import type { Bonds } from "@/lib/chem";
import { beadLabel, type BeadSize } from "@/lib/beads";
import { enumerateTerms, edgeKey } from "@/lib/topology";
import { distNm, angleDeg, dihedralDeg } from "@/lib/geom3";

// GROMACS/Martini 3 topology (.itp) writer.
//
// Connectivity comes from enumerateTerms (shared with the fitter). Equilibrium
// values are taken from fitted trajectory parameters when supplied, otherwise
// measured from the current single conformer. Force constants come from fitted
// params or documented defaults. This is a template to refine, not a validated
// force field.

export type ItpOptions = {
  bondK: number; // kJ/mol/nm^2
  angleK: number; // kJ/mol (cosine angle, funct 2)
  properK: number; // kJ/mol (proper dihedral, funct 1)
  properMult: number;
  improperK: number; // kJ/mol/rad^2 (improper, funct 2)
  ringBondsAsConstraints: boolean;
  properDihedrals: boolean;
  planarityImpropers: boolean;
};

export const DEFAULT_ITP_OPTIONS: ItpOptions = {
  bondK: 5000,
  angleK: 50,
  properK: 5,
  properMult: 1,
  improperK: 50,
  ringBondsAsConstraints: true,
  properDihedrals: true,
  planarityImpropers: true,
};

// Fitted parameters from Boltzmann inversion, keyed by canonical term key.
export type FittedParam = { equil: number; force: number };
export type FittedParams = Map<string, FittedParam>;

export const bondKeyOf = (i: number, j: number) => `b:${edgeKey(i, j)}`;
export const angleKeyOf = (a: number, b: number, c: number) => `a:${a}-${b}-${c}`;
export const properKeyOf = (i: number, j: number, k: number, l: number) =>
  `p:${i}-${j}-${k}-${l}`;

const MASS_BY_SIZE: Record<BeadSize, number> = { R: 72, S: 54, T: 36 };

const i5 = (n: number) => String(n).padStart(5);
const f = (v: number, d = 3) => v.toFixed(d);

export function buildItp(
  beads: Bead[],
  bonds: Bonds,
  fileName: string,
  options: ItpOptions = DEFAULT_ITP_OPTIONS,
  fitted?: FittedParams
): string {
  const molName =
    (fileName.replace(/^SMILES:\s*/i, "").replace(/\.[^.]+$/, "") || "MOL")
      .replace(/[^A-Za-z0-9]/g, "")
      .toUpperCase()
      .slice(0, 5) || "MOL";

  const pos = beads.map((b) => b.position);
  const terms = enumerateTerms(beads, bonds, options);

  const out: string[] = [];
  const push = (s = "") => out.push(s);

  const hasQ = beads.some((b) => b.type.startsWith("Q"));
  push("; Martini 3 topology generated by CG Molecule Mapper");
  push(`; source: ${fileName || "unknown"}`);
  if (fitted && fitted.size > 0) {
    push("; bonded parameters from Boltzmann inversion of an uploaded trajectory");
  } else {
    push("; NOTE: equilibrium values from a single conformer; force constants are");
    push(";       DEFAULT placeholders — parametrize from a trajectory or tune.");
  }
  if (hasQ)
    push("; NOTE: Q-type beads found — set their [ atoms ] charges manually.");
  push();

  push("[ moleculetype ]");
  push("; name   nrexcl");
  push(`${molName}     1`);
  push();

  push("[ atoms ]");
  push(";  nr    type  resnr residue  atom   cgnr    charge     mass");
  beads.forEach((b, i) => {
    const type = beadLabel(b.size, b.type);
    const mass = MASS_BY_SIZE[b.size];
    push(
      `${i5(i + 1)} ${type.padEnd(6)} ${i5(1)} ${molName.padEnd(6)} ` +
        `${b.name.slice(0, 5).padEnd(5)} ${i5(i + 1)}  ${f(0, 3).padStart(8)} ` +
        `${f(mass, 2).padStart(8)}`
    );
  });
  push();

  if (terms.bonds.length) {
    push("[ bonds ]");
    push(";  i     j  funct   length      Kb");
    for (const [i, j] of terms.bonds) {
      const fit = fitted?.get(bondKeyOf(i, j));
      const len = fit ? fit.equil : distNm(pos[i], pos[j]);
      const k = fit ? fit.force : options.bondK;
      push(`${i5(i + 1)} ${i5(j + 1)}     1   ${f(len)}   ${f(k, 1)}`);
    }
    push();
  }

  if (terms.constraints.length) {
    push("[ constraints ]");
    push(";  i     j  funct   length      ; rigid in-ring bonds");
    for (const [i, j] of terms.constraints) {
      const len = distNm(pos[i], pos[j]);
      push(`${i5(i + 1)} ${i5(j + 1)}     1   ${f(len)}`);
    }
    push();
  }

  if (terms.angles.length) {
    push("[ angles ]");
    push(";  i     j     k  funct   angle       Ka   ; funct 2 = Martini cosine");
    for (const [a, b, c] of terms.angles) {
      const fit = fitted?.get(angleKeyOf(a, b, c));
      const theta = fit ? fit.equil : angleDeg(pos[a], pos[b], pos[c]);
      const k = fit ? fit.force : options.angleK;
      push(
        `${i5(a + 1)} ${i5(b + 1)} ${i5(c + 1)}     2   ${f(theta, 1).padStart(7)}   ${f(k, 1)}`
      );
    }
    push();
  }

  if (terms.propers.length) {
    push("[ dihedrals ]");
    push(";  i     j     k     l  funct   angle       Kd  mult   ; proper");
    for (const [a, b, c, d] of terms.propers) {
      const fit = fitted?.get(properKeyOf(a, b, c, d));
      const phi = fit ? fit.equil : dihedralDeg(pos[a], pos[b], pos[c], pos[d]);
      const k = fit ? fit.force : options.properK;
      push(
        `${i5(a + 1)} ${i5(b + 1)} ${i5(c + 1)} ${i5(d + 1)}     1   ${f(phi, 1).padStart(7)}   ${f(k, 1)}   ${options.properMult}`
      );
    }
    push();
  }

  if (terms.impropers.length) {
    push("[ dihedrals ]");
    push(";  i     j     k     l  funct   angle       Ki   ; improper (planarity)");
    for (const [p, q, r, s] of terms.impropers) {
      push(
        `${i5(p + 1)} ${i5(q + 1)} ${i5(r + 1)} ${i5(s + 1)}     2   ${f(0, 1).padStart(7)}   ${f(options.improperK, 1)}`
      );
    }
    push();
  }

  if (terms.fusedSkipped > 0) {
    push(
      `; NOTE: ${terms.fusedSkipped} fused/complex aromatic ring system(s) not auto-flattened — add planarity impropers manually.`
    );
    push();
  }

  if (terms.rigidSystems.length) {
    const exclusionLines: string[] = [];
    for (const comp of terms.rigidSystems) {
      const sorted = [...comp].sort((a, b) => a - b);
      for (let x = 0; x < sorted.length; x++) {
        const partners = sorted
          .slice(x + 1)
          .map((v) => i5(v + 1))
          .join("");
        if (partners) exclusionLines.push(`${i5(sorted[x] + 1)}${partners}`);
      }
    }
    if (exclusionLines.length) {
      push("[ exclusions ]");
      push(";  within rigid rings");
      exclusionLines.forEach(push);
      push();
    }
  }

  return out.join("\n");
}
