// Generates a ready-to-run reference-MD bundle (OpenFF + OpenMM) for a loaded
// molecule. The user runs it on their machine/HPC; it writes a solute-only
// multi-model `traj.pdb` that is uploaded back for Boltzmann inversion.

export type MdOptions = {
  temperature: number; // K
  productionNs: number; // ns
};

export const DEFAULT_MD_OPTIONS: MdOptions = {
  temperature: 300,
  productionNs: 10,
};

function molName(fileName: string): string {
  return (
    (fileName.replace(/^SMILES:\s*/i, "").replace(/\.[^.]+$/, "") || "molecule")
      .replace(/[^A-Za-z0-9]/g, "")
      .slice(0, 20) || "molecule"
  );
}

export function buildEnvYml(): string {
  return [
    "name: cg-refmd",
    "channels:",
    "  - conda-forge",
    "dependencies:",
    "  - python=3.11",
    "  - openff-toolkit=0.16.*",
    "  - openmmforcefields=0.14.*",
    "  - openmm=8.1.*",
    "  - rdkit",
    "  - mdtraj",
    "",
  ].join("\n");
}

export function buildRunScript(
  fileName: string,
  smiles: string,
  opts: MdOptions
): string {
  const name = molName(fileName);
  return `#!/usr/bin/env python
"""
Reference all-atom MD for Martini CG parametrization.
Generated by CG Molecule Mapper.

Writes 'traj.pdb' - a multi-model, solute-only PDB trajectory. Upload that file
back into the app ("Parametrize from trajectory") to fit Martini bonded
parameters by Boltzmann inversion.

Tested against the versions pinned in environment.yml. If yours differ, check
the OpenFF / OpenMM release notes for API changes.
"""
import sys
from openmm import unit, LangevinMiddleIntegrator
from openmm.app import Simulation, PDBReporter, StateDataReporter
from openff.toolkit import Molecule
from openmmforcefields.generators import SystemGenerator

# ---- settings (baked in by the app) ----
SMILES        = ${JSON.stringify(smiles || "")}   # empty -> read molecule.pdb instead
MOL_NAME      = ${JSON.stringify(name)}
TEMPERATURE   = ${opts.temperature}          # kelvin
PRODUCTION_NS = ${opts.productionNs}         # nanoseconds
EQUIL_NS      = 0.5
TIMESTEP_FS   = 2.0
REPORT_PS     = 1.0                          # save a frame every REPORT_PS ps
FORCEFIELD    = "openff-2.2.0"               # small-molecule force field

# ---- build & parametrize the molecule ----
if SMILES:
    mol = Molecule.from_smiles(SMILES, allow_undefined_stereo=True)
else:
    mol = Molecule.from_file("molecule.pdb")
mol.generate_conformers(n_conformers=1)

system_generator = SystemGenerator(
    small_molecule_forcefield=FORCEFIELD,
    molecules=[mol],
    forcefield_kwargs={"constraints": None, "rigidWater": True},
)

topology  = mol.to_topology().to_openmm()
positions = mol.conformers[0].to_openmm()
system    = system_generator.create_system(topology)

# ---- integrate (vacuum, Langevin thermostat) ----
integrator = LangevinMiddleIntegrator(
    TEMPERATURE * unit.kelvin,
    1.0 / unit.picosecond,
    TIMESTEP_FS * unit.femtoseconds,
)
sim = Simulation(topology, system, integrator)
sim.context.setPositions(positions)

print("Minimizing energy ...")
sim.minimizeEnergy()
sim.context.setVelocitiesToTemperature(TEMPERATURE * unit.kelvin)

steps_per_ps = int(1000 / TIMESTEP_FS)
report_every = int(REPORT_PS * steps_per_ps)

print("Equilibrating ...")
sim.step(int(EQUIL_NS * 1000 * steps_per_ps))

print("Production ...")
sim.reporters.append(PDBReporter("traj.pdb", report_every))   # solute-only in vacuum
sim.reporters.append(
    StateDataReporter(
        sys.stdout, report_every * 10,
        step=True, potentialEnergy=True, temperature=True,
    )
)
sim.step(int(PRODUCTION_NS * 1000 * steps_per_ps))
print("Done -> traj.pdb")
`;
}

export function buildReadme(
  fileName: string,
  smiles: string,
  opts: MdOptions
): string {
  const name = molName(fileName);
  const src = smiles
    ? `SMILES \`${smiles}\``
    : "the bundled `molecule.pdb` (no SMILES was available)";
  return `# Reference MD for ${name}

This bundle runs a short all-atom simulation of your molecule and writes
\`traj.pdb\`, which you upload back into CG Molecule Mapper to fit Martini
bonded parameters (bonds, angles, dihedrals) by Boltzmann inversion.

Source structure: ${src}.

## 1. Create the environment
\`\`\`bash
conda env create -f environment.yml
conda activate cg-refmd
\`\`\`

## 2. Run the simulation
\`\`\`bash
python run_md.py          # writes traj.pdb (multi-model, solute-only)
\`\`\`
Roughly ${opts.productionNs} ns at ${opts.temperature} K; runtime depends on
molecule size and whether a GPU is available.

## 3. Bring it back
In the app, open **"Parametrize from trajectory"** and upload \`traj.pdb\`.
Each frame is mapped to your bead model, the bond/angle/dihedral distributions
are built, and a refined \`.itp\` is written.

## Notes
- Runs in **vacuum** for a fast, clean solute-only trajectory. For higher
  accuracy (especially dihedral populations) run in explicit solvent and strip
  the water before upload.
- Force field: **OpenFF Sage (openff-2.2.0)**. Set \`FORCEFIELD = "gaff-2.11"\`
  in \`run_md.py\` to use GAFF instead.
- Make sure the run is **equilibrated and long enough** that the distributions
  are smooth; increase \`PRODUCTION_NS\` for flexible molecules.
- This yields **direct Boltzmann inversion** parameters - excellent starting
  values, but validate against your reference before production use.
`;
}
