// SMILES for the building-block example molecules, so their 2D structures can
// be rendered. SMILES of named compounds are public chemical facts; stereo is
// dropped for clean thumbnails.

export const SMILES_BY_NAME: Record<string, string> = {
  "1,3-Dioxolane": "C1COCO1",
  "1-Methylimidazole": "Cn1ccnc1",
  "12-Butadiene": "C=C=CC",
  "2,5-dimethyl-1,4-benzoquinone": "CC1=CC(=O)C(C)=CC1=O",
  "2-Ethylpyrdine": "CCc1ccccn1",
  "2-Iodophenol": "Oc1ccccc1I",
  "2-Methyl-pyridine": "Cc1ccccn1",
  "2-Nitro-m-xylene": "Cc1cccc(C)c1[N+](=O)[O-]",
  "2-aminobenzenethiol": "Nc1ccccc1S",
  "2-bromophenol": "Oc1ccccc1Br",
  "2-chloroaniline": "Nc1ccccc1Cl",
  "2-methoxyfuran": "COc1ccco1",
  "2-methylhydroquinone": "Cc1cc(O)ccc1O",
  "4-Bromoanisole": "COc1ccc(Br)cc1",
  "4-Methylimidazole": "Cc1c[nH]cn1",
  "4-Nitroanisole": "COc1ccc([N+](=O)[O-])cc1",
  "4-bromobenzenesulfonamide": "NS(=O)(=O)c1ccc(Br)cc1",
  "4-methylsulfonylchlorobenzene": "CS(=O)(=O)c1ccc(Cl)cc1",
  Acetophenone: "CC(=O)c1ccccc1",
  Aniline: "Nc1ccccc1",
  Benzaldehyde: "O=Cc1ccccc1",
  Benzonitrile: "N#Cc1ccccc1",
  Benzotrifluoride: "FC(F)(F)c1ccccc1",
  Bromobenzene: "Brc1ccccc1",
  Butanone: "CCC(C)=O",
  Chlorobenzene: "Clc1ccccc1",
  Cyclohexene: "C1CCC=CC1",
  Cyclopentanol: "OC1CCCC1",
  Cyclopentanone: "O=C1CCCC1",
  "D-xylose": "OC1OCC(O)C(O)C1O",
  Ethylbenzene: "CCc1ccccc1",
  Iodobenzene: "Ic1ccccc1",
  Methoxybenzene: "COc1ccccc1",
  "Methyl acrylate": "COC(=O)C=C",
  "Methyl propanoate": "CCC(=O)OC",
  "Methyl-benzoate": "COC(=O)c1ccccc1",
  "Para-benzoquinone": "O=C1C=CC(=O)C=C1",
  Piperidine: "C1CCNCC1",
  Propaneamide: "CCC(N)=O",
  Pyridazine: "c1ccnnc1",
  Pyrrole: "c1cc[nH]c1",
  Pyrrolidine: "C1CCNC1",
  Tetrahydrofuran: "C1CCOC1",
  Tetrahydropyran: "C1CCOCC1",
  Thiophenol: "Sc1ccccc1",
  "benzene-1,2-diamine": "Nc1ccccc1N",
  benzenesulfonamide: "NS(=O)(=O)c1ccccc1",
  benzenesulfonamide_decoy: "NS(=O)(=O)c1ccccc1",
  butanal: "CCCC=O",
  butanol: "CCCCO",
  dimethylsulfoxide: "CS(C)=O",
  ethylacetate: "CCOC(C)=O",
  hexanal: "CCCCCC=O",
  hexene: "CCCCC=C",
  hexyne: "CCCCC#C",
  "n-butyl acetate": "CCCCOC(C)=O",
  "n-pentylamine": "CCCCCN",
  "ortho-Methylanisole": "COc1ccccc1C",
  "p-Cresol": "Cc1ccc(O)cc1",
  "propionic acid": "CCC(=O)O",
  "pyridazine, 3,6-dichloro-": "Clc1ccc(Cl)nn1",
  trifluoroethanol: "OCC(F)(F)F",
};

export function smilesForName(name: string): string | undefined {
  return SMILES_BY_NAME[name];
}
